# Generated by Django 5.1.6 on 2025-02-13 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0002_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='Company',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='Position',
            new_name='position',
        ),
    ]
